# ------------------------ Mock Endpoints ------------------------
GET localhost:7007/api/mock

###

GET localhost:7007/api/mock/999

###

POST localhost:7007/api/mock
Content-Type: application/json

{
  "name": "Batman",
  "plantType": "Spring Bloom",
  "price": 180.00,
  "maxHeight": 200
}

###

GET localhost:7007/api/mock/type/Rose



# ------------------------ Plant Endpoints ------------------------

###
#get all plants
GET localhost:7007/api/plant

###

#get plant with id = 1
GET localhost:7007/api/plant/999

###

#add a new plant to dataase
POST localhost:7007/api/plant
Content-Type: application/json

{
  "name": "",
  "plantType": "Spring Bloom",
  "price": 180.00,
  "maxHeight": 300
}

###

#good fejl med "plant/Rose
# dårlig fejl med "type/Rose" why?
GET localhost:7007/api/plant/type/Rose

###


